package kube.model.action;

public enum ActionType {

    /**********
    * MODEL
    **********/

    // --- GAME ---
    SHOW_ALL,
    SHOW_MOUNTAIN,
    SWAP,
    SHUFFLE,
    VALIDATE,
    MOVE,
    MOVE_NUMBER,
    UNDO,
    REDO,
    PRINT_AI,
    PRINT_COMMAND_ERROR,
    PRINT_WAIT_COORDINATES,
    PRINT_GOODBYE,
    PRINT_HELP,
    PRINT_LIST_MOVES,
    PRINT_NEXT_PLAYER,
    PRINT_PLAYER,
    PRINT_PLAYER_NAME,
    PRINT_START,
    PRINT_STATE,
    PRINT_WELCOME,
    PRINT_WIN_MESSAGE,
    PRINT_FORBIDDEN_ACTION,
    PRINT_ASK_NB_PLAYERS,
    PRINT_ASK_PLAYER_NAME,
    PRINT_ASK_GAME_MODE,

    // --- NETWORK ---
    PRINT_ASK_HOST_OR_JOIN,
    PRINT_ASK_IP,
    INIT_K3,
    OTHER_PLAYER,
    PRINT_WAITING_FOR_CONNECTION,
    PRINT_CONNECTION_ETABLISHED,
    PRINT_CONNECTION_ERROR,
    PRINT_NOT_YOUR_TURN,
    ITS_YOUR_TURN,
    MOVE_FROM_NETWORK,
    PLAYER_DATA,
    ACKNOWLEDGEMENT,
    PRINT_WAITING_RESPONSE,
    CONNECTION_CLOSED,

    /**********
    * GUI
    **********/

    // --- GLOBAL ---
    SET_BUTTON_PRESSED,
    SET_BUTTON_HOVERED,
    SET_BUTTON_RELEASED,
    SET_BUTTON_CLICKED,
    SET_BUTTON_DEFAULT,
    SETTINGS,

    // --- MENU ---
    PLAY_ONLINE,
    PLAY_LOCAL,
    RULES,
    VOLUME,

    // --- PHASE 1 ---
    GRAB_HEX,

    // --- PHASE 2 ---

    // --- Overlay ---
    ADD_GLASS,
    REMOVE_GLASS,
}